name: Run Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with: 
          path: "."
      - name: Checkout hakai metadata filesxz
        uses: actions/checkout@v5
        with:
          repository: HakaiInstitute/hakai-metadata-entry-form-files
          path: ./tests/records/hakai-metadata-entry-form-files

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --dev

      - name: Lint Tests
        shell: bash -l {0}
        run: |
          uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
          uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv
      - name: Run tests
        run: |
          uv run pytest tests/ 
      - name: Convert test record to CITATION.cff if main branch
        uses: hakaiinstitute/hakai-metadata-conversion@main
        if: github.ref == 'refs/heads/main'
        with:
          input: tests/records/test_record1.json
          output-file: CITATION.cff
          output-format: cff
          commit: false

      # re-deploy the metadata web app on caprover as it uses this repo
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Caprover CLI
        run: npm install -g caprover
      
      - name: Tell Caprover server to deploy main (https://metadata-generator-web.server.hakai.app)
        run: caprover deploy --caproverUrl https://captain.server.hakai.app --appToken ${{ secrets.CAPROVER_TOKEN_MAIN }} --branch 'main' --appName metadata-generator-web