name: Run Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout hakai metadata files
        uses: actions/checkout@v4
        with:
          repository: HakaiInstitute/hakai-metadata-entry-form-files
          path: tests/records
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
      
      - name: Convert test record to CITATION.cff
        uses: hakaiinstitute/hakai-metadata-conversion@main
        with:
          input: tests/records/test_record1.json
          output-file: CITATION.cff
          output-format: cff
          commit: false
