name: Run Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
    
  action:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run local action
        uses: ./action.yaml
        with:
          input: tests/records/test_record1.json
          output-file: CITATION.cff
          output-format: cff
          commit: false
      - name: Install cffconvert
        run: pip install cffconvert
      - name: Validate CITATION.cff
        run: cffconvert validate CITATION.cff
      - name: Convert CITATION.cff to CITATION.bib
        run: cffconvert CITATION.cff --format=bib